name: publish

permissions: 
  contents: write

on:
  push:
    branches: [main]
  # schedule:
  #    - cron: "12 15 * * *"

jobs:
  create_and_publish_video:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.8"

      - run: python -m pip install -U pip
      - run: python -m pip install -r requirements.txt
      - run: sudo apt-get update
      - run: sudo apt-get install ffmpeg -y
      - run: sudo apt-get install timidity -y
      - run: python .
      - name: Release to main
        uses: softprops/action-gh-release@v2
        id: release
        with:
          files: output.mp4
          tag_name: ${{ github.run_number }}
        if: github.ref == 'refs/heads/main'

      - name: Compute post time 1 hour from now
        id: post_time
        run: |
          POST_TIME=$(date -u -d '1 hour' '+%Y-%m-%dT%H:%M:%SZ')
          echo "post_time=$POST_TIME" >> $GITHUB_OUTPUT

      - run: python release_to_buffer.py \
              "${{ secrets.BUFFER_API_KEY }}" \
              "${{ secrets.BUFFER_CHANNEL_ID }}" \
              "${{ steps.post_time.outputs.post_time }}" \
              "https://github.com/Jung-Choi-01/random-midi-twitter/releases/download/${{github.run_number}}/output.mp4" \
              "Automated post text for the scheduled Buffer video update."